### ISSUE TITLE
Fails to compile with libxml version >= 2.9

### ISSUE THREAD

**Issue by cicku** [ccontavalli/mod-xslt#5]
%configure \
   --with-sapi=apache2 \
   --with-apr-config=%{_bindir}/apr-1-config \
   --with-apu-config=%{_bindir}/apu-1-config \
   --with-apxs=%{_httpd_apxs}
make %{?_smp_mflags}

Here is the log:

Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.3mDGZn
- umask 022
- cd /home/rpmaker/rpmbuild/BUILD
- cd /home/rpmaker/rpmbuild/BUILD
- rm -rf mod-xslt-1.4.3
- /usr/bin/tar -xf -
- /usr/bin/gzip -dc /home/rpmaker/rpmbuild/SOURCES/v1.4.3.tar.gz
- STATUS=0
- '[' 0 -ne 0 ']'
- cd mod-xslt-1.4.3
- /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
- exit 0
  Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.0sdvzd
- umask 022
- cd /home/rpmaker/rpmbuild/BUILD
- cd mod-xslt-1.4.3
- CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables'
- export CFLAGS
- CXXFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables'
- export CXXFLAGS
- FFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -I/usr/lib/gfortran/modules'
- export FFLAGS
- FCFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -I/usr/lib/gfortran/modules'
- export FCFLAGS
- LDFLAGS='-Wl,-z,relro '
- export LDFLAGS
  ++ find . -name config.guess -o -name config.sub
- for i in '$(find . -name config.guess -o -name config.sub)'
  ++ basename ./helpers/config.sub
- '[' -f /usr/lib/rpm/redhat/config.sub ']'
- /usr/bin/rm -f ./helpers/config.sub
  ++ basename ./helpers/config.sub
- /usr/bin/cp -fv /usr/lib/rpm/redhat/config.sub ./helpers/config.sub
  '/usr/lib/rpm/redhat/config.sub' -> './helpers/config.sub'
- for i in '$(find . -name config.guess -o -name config.sub)'
  ++ basename ./helpers/config.guess
- '[' -f /usr/lib/rpm/redhat/config.guess ']'
- /usr/bin/rm -f ./helpers/config.guess
  ++ basename ./helpers/config.guess
- /usr/bin/cp -fv /usr/lib/rpm/redhat/config.guess ./helpers/config.guess
  '/usr/lib/rpm/redhat/config.guess' -> './helpers/config.guess'
- ./configure --build=i686-redhat-linux-gnu --host=i686-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-sapi=apache2 --with-apr-config=/usr/bin/apr-1-config --with-apu-config=/usr/bin/apu-1-config --with-apxs=/usr/bin/apxs
  configure: WARNING: unrecognized options: --disable-dependency-tracking
  checking for i686-redhat-linux-gnu-gcc... no
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking for a BSD-compatible install... /bin/install -c
  checking whether make sets $(MAKE)... yes
  checking build system type... i686-redhat-linux-gnu
  checking host system type... i686-redhat-linux-gnu
  checking how to print strings... printf
  checking for a sed that does not truncate output... /bin/sed
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for fgrep... /bin/grep -F
  checking for ld used by gcc... /bin/ld
  checking if the linker (/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
  checking the name lister (/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking whether the shell understands some XSI constructs... yes
  checking whether the shell understands "+="... yes
  checking how to convert i686-redhat-linux-gnu file names to i686-redhat-linux-gnu format... func_convert_file_noop
  checking how to convert i686-redhat-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /bin/ld option to reload object files... -r
  checking for i686-redhat-linux-gnu-objdump... no
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for i686-redhat-linux-gnu-dlltool... no
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for i686-redhat-linux-gnu-ar... no
  checking for ar... ar
  checking for archiver @FILE support... @
  checking for i686-redhat-linux-gnu-strip... no
  checking for strip... strip
  checking for i686-redhat-linux-gnu-ranlib... no
  checking for ranlib... ranlib
  checking for gawk... gawk
  checking command to parse /bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for i686-redhat-linux-gnu-mt... no
  checking for mt... no
  checking if : is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... no
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/bin/ld) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... yes
  configure: creating ./config.lt
  config.lt: creating libtool
  checking for malloc... yes
  checking for memcmp... yes
  checking for memset... yes
  checking for realloc... yes
  checking for stat... yes
  checking for vprintf... yes
  checking for memset... (cached) yes
  checking for strdup... yes
  checking for stdlib.h... (cached) yes
  checking for unistd.h... (cached) yes
  checking for sys/param.h... yes
  checking for getpagesize... yes
  checking for working mmap... yes
  checking for working memcmp... yes
  checking for stdint types... stdint.h (shortcircuit)
  make use of stdint.h in lib/modxslt1/modxslt-integers.h (assuming C99 compatible system)
  checking for library containing strerror... none required
  checking for an ANSI C-conforming const... yes
  checking for inline... inline
  checking for function prototypes... yes
  checking for size_t... yes
  checking for ANSI C header files... (cached) yes
  checking for stdlib.h... (cached) yes
  checking fcntl.h usability... yes
  checking fcntl.h presence... yes
  checking for fcntl.h... yes
  checking for string.h... (cached) yes
  checking for unistd.h... (cached) yes
  checking syslog.h usability... yes
  checking syslog.h presence... yes
  checking for syslog.h... yes
  checking for xml2-config... /bin/xml2-config
  checking for xslt-config... /bin/xslt-config
  checking for pcre-config... /bin/pcre-config
  checking for xmlParseMemory in -lxml2... yes
  checking for xsltApplyStylesheet in -lxslt... yes
  checking for pcre_compile in -lpcre... yes
  checking for xsltCopyTextString in -lxslt... yes
  checking libxml/uri.h usability... yes
  checking libxml/uri.h presence... yes
  checking for libxml/uri.h... yes
  checking libxml/tree.h usability... yes
  checking libxml/tree.h presence... yes
  checking for libxml/tree.h... yes
  checking libxml/parserInternals.h usability... yes
  checking libxml/parserInternals.h presence... yes
  checking for libxml/parserInternals.h... yes
  checking libxml/nanohttp.h usability... yes
  checking libxml/nanohttp.h presence... yes
  checking for libxml/nanohttp.h... yes
  checking for xmlGetGlobalState in -lxml2... yes
  checking for xmlNanoHTTPCtxt... no
  configure: WARNING:
  ******************************************************
- Your libxml2 does not let applications access xmlNanoHTTPCtxt.
- This is not bad by itself, but any 404 or 403 or any error page
- returned by a remote host as a response to the request of a
- stylesheet or a dtd will be parsed as xml, leading to weird
- results. If you can live with it, ignore this warning.
- Ignore this warning also if you patched your library with
-     patches/libxml.httpstatus.diff
- which cannot be easily detected. In any other case, you can
- apply the patch:
-     patches/libxml.httpcontextexport.diff
- If you need further help, please read the doc/patches/patches.txt
- Compilation will go on anyway without problems.
  ******************************************************
  checking for xmlSetGlobalState in -lxml2... no
  configure: WARNING:
  ******************************************************
- Your libxml2 does not provide a setGlobalState.
- You probably haven't patched it. Please read the manual, doc/manual/manual.txt.
- Compilation will go on anyway - I will compile a small compatibility layer.
  ******************************************************
  checking libxslt/xslt.h usability... yes
  checking libxslt/xslt.h presence... yes
  checking for libxslt/xslt.h... yes
  checking libxslt/xsltInternals.h usability... yes
  checking libxslt/xsltInternals.h presence... yes
  checking for libxslt/xsltInternals.h... yes
  checking libxslt/transform.h usability... yes
  checking libxslt/transform.h presence... yes
  checking for libxslt/transform.h... yes
  checking libxslt/xsltutils.h usability... yes
  checking libxslt/xsltutils.h presence... yes
  checking for libxslt/xsltutils.h... yes
  checking libexslt/exslt.h usability... yes
  checking libexslt/exslt.h presence... yes
  checking for libexslt/exslt.h... yes
  checking for exsltLibraryVersion in -lexslt... yes
  checking pcre.h usability... yes
  checking pcre.h presence... yes
  checking for pcre.h... yes
  configure: checking if pointers (void *) are at least 32 bits long...
  configure: \* Trying with: 'apache2'
  configure: WARNING:
- Apache has been compiled with a different compiler than the specified (or detected) one!
- I will use the same compiler as used by apache: 'gcc -std=gnu99'
- I'm also assuming 'gcc -std=gnu99' is ISO C and POSIX compliant.
  checking for apr_palloc in -lapr-1... yes
  checking for apr_brigade_create in -laprutil-1... yes
  configure: WARNING:
  ********************************************
- Generating Makefiles and headers for
- mod-xslt to be used with:
-             \* apache2 *
  *******************************************\* 
  checking pthread.h usability... yes
  checking pthread.h presence... yes
  checking for pthread.h... yes
  checking for pthread_setspecific in -lpthread... yes
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating utils/Makefile
  config.status: creating lib/Makefile
  config.status: creating lib/parser/Makefile
  config.status: creating sapi/apache1/Makefile
  config.status: creating sapi/apache2/Makefile
  config.status: creating sapi/none/Makefile
  config.status: creating utils/modxslt-config.pre
  config.status: creating doc/man/Makefile
  config.status: creating lib/modxslt1/modxslt-system.h
  config.status: executing libtool commands
  config.status: executing lib/modxslt1/modxslt-integers.h commands
  config.status: creating lib/modxslt1/modxslt-integers.h : __LIB_MODXSLT1_MODXSLT_INTEGERS_H
  configure: WARNING: unrecognized options: --disable-dependency-tracking
- make -j3
  make -C lib all
  make[1]: Entering directory `/home/rpmaker/rpmbuild/BUILD/mod-xslt-1.4.3/lib'
  make -C parser all
  make[2]: Entering directory`/home/rpmaker/rpmbuild/BUILD/mod-xslt-1.4.3/lib/parser'
- COMPILING modxslt-table.c
- COMPILING modxslt-io.c
- COMPILING modxslt-screen-expr.parser.c
- COMPILING modxslt-url.c
- COMPILING modxslt-memory.c
- COMPILING modxslt-screen-expr.lexer.c
- COMPILING modxslt-opr-bool.c
  ../../../lib/parser/modxslt-screen-expr.lexer.c:1842:17: warning: 'yyunput' defined but not used [-Wunused-function]
  ../../../lib/parser/modxslt-screen-expr.lexer.c:1893:16: warning: 'input' defined but not used [-Wunused-function]
  make[2]: Leaving directory `/home/rpmaker/rpmbuild/BUILD/mod-xslt-1.4.3/lib/parser'
- COMPILING modxslt-opr-cmp.c
- COMPILING modxslt-doc.c
- COMPILING modxslt-libxml.c
- COMPILING modxslt-table-algo.c
- COMPILING modxslt-debug.c
  modxslt-libxml.c: In function 'mxslt_doc_xml_parse':
  modxslt-libxml.c:538:33: error: dereferencing pointer to incomplete type
  input->base=input->buf->buffer->content;
                               ^
  modxslt-libxml.c:539:32: error: dereferencing pointer to incomplete type
  input->cur=input->buf->buffer->content;
                              ^
  modxslt-libxml.c:540:33: error: dereferencing pointer to incomplete type
  input->end=&input->buf->buffer->content[input->buf->buffer->use];
                               ^
  modxslt-libxml.c:540:61: error: dereferencing pointer to incomplete type
  input->end=&input->buf->buffer->content[input->buf->buffer->use];
                                                           ^
  make[1]: **\* [modxslt-libxml.lo] Error 1
  make[1]: **\* Waiting for unfinished jobs....
  make[1]: Leaving directory `/home/rpmaker/rpmbuild/BUILD/mod-xslt-1.4.3/lib'
  make: **\* [library] Error 2
  error: Bad exit status from /var/tmp/rpm-tmp.0sdvzd (%build)

**Comment by cicku** [comment]
[rpmaker@fab SPECS]$ rpm -qa|grep gcc
gcc-4.8.1-2.fc20.i686

**Comment by ccontavalli** [comment]
Just to confirm, this is on fedora 19?

at least by this schedule, fedora 20 does not exist yet, right?
http://fedoraproject.org/wiki/Releases/20/Schedule

(trying to reproduce the exact error to verify fix)

**Comment by ccontavalli** [comment]
Also, could you confirm libxslt and libxml version? Thanks.

**Comment by cicku** [comment]
This is on Fedora Rawhide.

[root@fab usr]# rpm -qa|grep  "libxslt|libxml"
libxslt-devel-1.1.28-3.fc20.i686
libxml2-devel-2.9.1-1.fc20.i686
libxml++-2.36.0-2.fc19.i686
libxslt-1.1.28-3.fc20.i686
libxml2-2.9.1-1.fc20.i686
libxml2-python-2.9.1-1.fc20.i686

**Comment by ccontavalli** [comment]
Ok, the issue is with libxml 2.9, with libxml 2.8 build process works fine. Fix in progress..

**Comment by ccontavalli** [comment]
You can find a fix here:
https://gist.github.com/ccontavalli/5944029

it would be great if you could patch and verify that it fixes the problem. It may take me a bit longer to submit to head as I need to verify the fix with older versions of libxml, and maybe add some configure plumbing.
